/**
 * Seed Script: All F1 Tracks with Complete Data
 * 
 * Run with: npx tsx prisma/seed-tracks.ts
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// F1 Media CDN base URL
const F1_MEDIA_CDN = "https://media.formula1.com/image/upload";

// Helper to generate F1 CDN image URLs
const getCircuitImageUrl = (countryName: string) => 
  `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Circuit%20maps%2016x9/${countryName}_Circuit.png`;

// Country code to flag emoji mapping
const countryFlags: Record<string, string> = {
  BH: "🇧🇭", SA: "🇸🇦", AU: "🇦🇺", JP: "🇯🇵", CN: "🇨🇳",
  US: "🇺🇸", IT: "🇮🇹", MC: "🇲🇨", CA: "🇨🇦", ES: "🇪🇸",
  AT: "🇦🇹", GB: "🇬🇧", HU: "🇭🇺", BE: "🇧🇪", NL: "🇳🇱",
  AZ: "🇦🇿", SG: "🇸🇬", MX: "🇲🇽", BR: "🇧🇷", QA: "🇶🇦",
  AE: "🇦🇪", PT: "🇵🇹", RU: "🇷🇺", TR: "🇹🇷", DE: "🇩🇪",
  FR: "🇫🇷", MY: "🇲🇾", KR: "🇰🇷", IN: "🇮🇳", ZA: "🇿🇦",
};

// Comprehensive F1 Track Data
const F1_TRACKS = [
  {
    name: "Bahrain International Circuit",
    shortName: "BAH",
    country: "Bahrain",
    countryCode: "BH",
    city: "Sakhir",
    length: 5.412,
    defaultLaps: 57,
    raceDistance: 308.238,
    turns: 15,
    firstGrandPrix: 2004,
    lapRecord: "1:31.447",
    lapRecordHolder: "Pedro de la Rosa",
    lapRecordYear: 2005,
    timezone: "Asia/Bahrain",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Bahrain.jpg`,
    miniImageUrl: getCircuitImageUrl("Bahrain"),
    layoutImageUrl: getCircuitImageUrl("Bahrain"),
  },
  {
    name: "Jeddah Corniche Circuit",
    shortName: "JED",
    country: "Saudi Arabia",
    countryCode: "SA",
    city: "Jeddah",
    length: 6.174,
    defaultLaps: 50,
    raceDistance: 308.45,
    turns: 27,
    firstGrandPrix: 2021,
    lapRecord: "1:30.734",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2021,
    timezone: "Asia/Riyadh",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Saudi_Arabia.jpg`,
    miniImageUrl: getCircuitImageUrl("Saudi_Arabia"),
    layoutImageUrl: getCircuitImageUrl("Saudi_Arabia"),
  },
  {
    name: "Albert Park Circuit",
    shortName: "AUS",
    country: "Australia",
    countryCode: "AU",
    city: "Melbourne",
    length: 5.278,
    defaultLaps: 58,
    raceDistance: 306.124,
    turns: 14,
    firstGrandPrix: 1996,
    lapRecord: "1:19.813",
    lapRecordHolder: "Charles Leclerc",
    lapRecordYear: 2024,
    timezone: "Australia/Melbourne",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Australia.jpg`,
    miniImageUrl: getCircuitImageUrl("Australia"),
    layoutImageUrl: getCircuitImageUrl("Australia"),
  },
  {
    name: "Suzuka International Racing Course",
    shortName: "SUZ",
    country: "Japan",
    countryCode: "JP",
    city: "Suzuka",
    length: 5.807,
    defaultLaps: 53,
    raceDistance: 307.471,
    turns: 18,
    firstGrandPrix: 1987,
    lapRecord: "1:30.983",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2019,
    timezone: "Asia/Tokyo",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Japan.jpg`,
    miniImageUrl: getCircuitImageUrl("Japan"),
    layoutImageUrl: getCircuitImageUrl("Japan"),
  },
  {
    name: "Shanghai International Circuit",
    shortName: "SHA",
    country: "China",
    countryCode: "CN",
    city: "Shanghai",
    length: 5.451,
    defaultLaps: 56,
    raceDistance: 305.066,
    turns: 16,
    firstGrandPrix: 2004,
    lapRecord: "1:32.238",
    lapRecordHolder: "Michael Schumacher",
    lapRecordYear: 2004,
    timezone: "Asia/Shanghai",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/China.jpg`,
    miniImageUrl: getCircuitImageUrl("China"),
    layoutImageUrl: getCircuitImageUrl("China"),
  },
  {
    name: "Miami International Autodrome",
    shortName: "MIA",
    country: "United States",
    countryCode: "US",
    city: "Miami",
    length: 5.412,
    defaultLaps: 57,
    raceDistance: 308.326,
    turns: 19,
    firstGrandPrix: 2022,
    lapRecord: "1:29.708",
    lapRecordHolder: "Max Verstappen",
    lapRecordYear: 2023,
    timezone: "America/New_York",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Miami.jpg`,
    miniImageUrl: getCircuitImageUrl("Miami"),
    layoutImageUrl: getCircuitImageUrl("Miami"),
  },
  {
    name: "Autodromo Enzo e Dino Ferrari",
    shortName: "IMO",
    country: "Italy",
    countryCode: "IT",
    city: "Imola",
    length: 4.909,
    defaultLaps: 63,
    raceDistance: 309.049,
    turns: 19,
    firstGrandPrix: 1980,
    lapRecord: "1:15.484",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2020,
    timezone: "Europe/Rome",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Emilia_Romagna.jpg`,
    miniImageUrl: getCircuitImageUrl("Emilia_Romagna"),
    layoutImageUrl: getCircuitImageUrl("Emilia_Romagna"),
  },
  {
    name: "Circuit de Monaco",
    shortName: "MON",
    country: "Monaco",
    countryCode: "MC",
    city: "Monte Carlo",
    length: 3.337,
    defaultLaps: 78,
    raceDistance: 260.286,
    turns: 19,
    firstGrandPrix: 1950,
    lapRecord: "1:12.909",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2021,
    timezone: "Europe/Monaco",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Monaco.jpg`,
    miniImageUrl: getCircuitImageUrl("Monaco"),
    layoutImageUrl: getCircuitImageUrl("Monaco"),
  },
  {
    name: "Circuit Gilles Villeneuve",
    shortName: "MTL",
    country: "Canada",
    countryCode: "CA",
    city: "Montreal",
    length: 4.361,
    defaultLaps: 70,
    raceDistance: 305.27,
    turns: 14,
    firstGrandPrix: 1978,
    lapRecord: "1:13.078",
    lapRecordHolder: "Valtteri Bottas",
    lapRecordYear: 2019,
    timezone: "America/Toronto",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Canada.jpg`,
    miniImageUrl: getCircuitImageUrl("Canada"),
    layoutImageUrl: getCircuitImageUrl("Canada"),
  },
  {
    name: "Circuit de Barcelona-Catalunya",
    shortName: "BCN",
    country: "Spain",
    countryCode: "ES",
    city: "Barcelona",
    length: 4.657,
    defaultLaps: 66,
    raceDistance: 307.236,
    turns: 14,
    firstGrandPrix: 1991,
    lapRecord: "1:16.330",
    lapRecordHolder: "Max Verstappen",
    lapRecordYear: 2023,
    timezone: "Europe/Madrid",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Spain.jpg`,
    miniImageUrl: getCircuitImageUrl("Spain"),
    layoutImageUrl: getCircuitImageUrl("Spain"),
  },
  {
    name: "Red Bull Ring",
    shortName: "RBR",
    country: "Austria",
    countryCode: "AT",
    city: "Spielberg",
    length: 4.318,
    defaultLaps: 71,
    raceDistance: 306.452,
    turns: 10,
    firstGrandPrix: 1970,
    lapRecord: "1:05.619",
    lapRecordHolder: "Carlos Sainz",
    lapRecordYear: 2020,
    timezone: "Europe/Vienna",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Austria.jpg`,
    miniImageUrl: getCircuitImageUrl("Austria"),
    layoutImageUrl: getCircuitImageUrl("Austria"),
  },
  {
    name: "Silverstone Circuit",
    shortName: "SIL",
    country: "United Kingdom",
    countryCode: "GB",
    city: "Silverstone",
    length: 5.891,
    defaultLaps: 52,
    raceDistance: 306.198,
    turns: 18,
    firstGrandPrix: 1950,
    lapRecord: "1:27.097",
    lapRecordHolder: "Max Verstappen",
    lapRecordYear: 2020,
    timezone: "Europe/London",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Great_Britain.jpg`,
    miniImageUrl: getCircuitImageUrl("Great_Britain"),
    layoutImageUrl: getCircuitImageUrl("Great_Britain"),
  },
  {
    name: "Hungaroring",
    shortName: "HUN",
    country: "Hungary",
    countryCode: "HU",
    city: "Budapest",
    length: 4.381,
    defaultLaps: 70,
    raceDistance: 306.63,
    turns: 14,
    firstGrandPrix: 1986,
    lapRecord: "1:16.627",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2020,
    timezone: "Europe/Budapest",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Hungary.jpg`,
    miniImageUrl: getCircuitImageUrl("Hungary"),
    layoutImageUrl: getCircuitImageUrl("Hungary"),
  },
  {
    name: "Circuit de Spa-Francorchamps",
    shortName: "SPA",
    country: "Belgium",
    countryCode: "BE",
    city: "Stavelot",
    length: 7.004,
    defaultLaps: 44,
    raceDistance: 308.052,
    turns: 19,
    firstGrandPrix: 1950,
    lapRecord: "1:46.286",
    lapRecordHolder: "Valtteri Bottas",
    lapRecordYear: 2018,
    timezone: "Europe/Brussels",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Belgium.jpg`,
    miniImageUrl: getCircuitImageUrl("Belgium"),
    layoutImageUrl: getCircuitImageUrl("Belgium"),
  },
  {
    name: "Circuit Zandvoort",
    shortName: "ZAN",
    country: "Netherlands",
    countryCode: "NL",
    city: "Zandvoort",
    length: 4.259,
    defaultLaps: 72,
    raceDistance: 306.587,
    turns: 14,
    firstGrandPrix: 1952,
    lapRecord: "1:11.097",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2021,
    timezone: "Europe/Amsterdam",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Netherlands.jpg`,
    miniImageUrl: getCircuitImageUrl("Netherlands"),
    layoutImageUrl: getCircuitImageUrl("Netherlands"),
  },
  {
    name: "Autodromo Nazionale Monza",
    shortName: "MNZ",
    country: "Italy",
    countryCode: "IT",
    city: "Monza",
    length: 5.793,
    defaultLaps: 53,
    raceDistance: 306.72,
    turns: 11,
    firstGrandPrix: 1950,
    lapRecord: "1:21.046",
    lapRecordHolder: "Rubens Barrichello",
    lapRecordYear: 2004,
    timezone: "Europe/Rome",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Italy.jpg`,
    miniImageUrl: getCircuitImageUrl("Italy"),
    layoutImageUrl: getCircuitImageUrl("Italy"),
  },
  {
    name: "Baku City Circuit",
    shortName: "BAK",
    country: "Azerbaijan",
    countryCode: "AZ",
    city: "Baku",
    length: 6.003,
    defaultLaps: 51,
    raceDistance: 306.049,
    turns: 20,
    firstGrandPrix: 2016,
    lapRecord: "1:43.009",
    lapRecordHolder: "Charles Leclerc",
    lapRecordYear: 2019,
    timezone: "Asia/Baku",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Azerbaijan.jpg`,
    miniImageUrl: getCircuitImageUrl("Azerbaijan"),
    layoutImageUrl: getCircuitImageUrl("Azerbaijan"),
  },
  {
    name: "Marina Bay Street Circuit",
    shortName: "SIN",
    country: "Singapore",
    countryCode: "SG",
    city: "Singapore",
    length: 4.94,
    defaultLaps: 62,
    raceDistance: 306.143,
    turns: 19,
    firstGrandPrix: 2008,
    lapRecord: "1:35.867",
    lapRecordHolder: "Lewis Hamilton",
    lapRecordYear: 2023,
    timezone: "Asia/Singapore",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Singapore.jpg`,
    miniImageUrl: getCircuitImageUrl("Singapore"),
    layoutImageUrl: getCircuitImageUrl("Singapore"),
  },
  {
    name: "Circuit of the Americas",
    shortName: "COTA",
    country: "United States",
    countryCode: "US",
    city: "Austin",
    length: 5.513,
    defaultLaps: 56,
    raceDistance: 308.405,
    turns: 20,
    firstGrandPrix: 2012,
    lapRecord: "1:36.169",
    lapRecordHolder: "Charles Leclerc",
    lapRecordYear: 2019,
    timezone: "America/Chicago",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/USA.jpg`,
    miniImageUrl: getCircuitImageUrl("USA"),
    layoutImageUrl: getCircuitImageUrl("USA"),
  },
  {
    name: "Autódromo Hermanos Rodríguez",
    shortName: "MEX",
    country: "Mexico",
    countryCode: "MX",
    city: "Mexico City",
    length: 4.304,
    defaultLaps: 71,
    raceDistance: 305.354,
    turns: 17,
    firstGrandPrix: 1963,
    lapRecord: "1:17.774",
    lapRecordHolder: "Valtteri Bottas",
    lapRecordYear: 2021,
    timezone: "America/Mexico_City",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Mexico.jpg`,
    miniImageUrl: getCircuitImageUrl("Mexico"),
    layoutImageUrl: getCircuitImageUrl("Mexico"),
  },
  {
    name: "Autódromo José Carlos Pace",
    shortName: "INT",
    country: "Brazil",
    countryCode: "BR",
    city: "São Paulo",
    length: 4.309,
    defaultLaps: 71,
    raceDistance: 305.879,
    turns: 15,
    firstGrandPrix: 1973,
    lapRecord: "1:10.540",
    lapRecordHolder: "Valtteri Bottas",
    lapRecordYear: 2018,
    timezone: "America/Sao_Paulo",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Brazil.jpg`,
    miniImageUrl: getCircuitImageUrl("Brazil"),
    layoutImageUrl: getCircuitImageUrl("Brazil"),
  },
  {
    name: "Las Vegas Street Circuit",
    shortName: "LVS",
    country: "United States",
    countryCode: "US",
    city: "Las Vegas",
    length: 6.201,
    defaultLaps: 50,
    raceDistance: 310.05,
    turns: 17,
    firstGrandPrix: 2023,
    lapRecord: "1:35.490",
    lapRecordHolder: "Oscar Piastri",
    lapRecordYear: 2024,
    timezone: "America/Los_Angeles",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Las_Vegas.jpg`,
    miniImageUrl: getCircuitImageUrl("Las_Vegas"),
    layoutImageUrl: getCircuitImageUrl("Las_Vegas"),
  },
  {
    name: "Lusail International Circuit",
    shortName: "LUS",
    country: "Qatar",
    countryCode: "QA",
    city: "Lusail",
    length: 5.419,
    defaultLaps: 57,
    raceDistance: 308.611,
    turns: 16,
    firstGrandPrix: 2021,
    lapRecord: "1:24.319",
    lapRecordHolder: "Max Verstappen",
    lapRecordYear: 2023,
    timezone: "Asia/Qatar",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Qatar.jpg`,
    miniImageUrl: getCircuitImageUrl("Qatar"),
    layoutImageUrl: getCircuitImageUrl("Qatar"),
  },
  {
    name: "Yas Marina Circuit",
    shortName: "YAS",
    country: "United Arab Emirates",
    countryCode: "AE",
    city: "Abu Dhabi",
    length: 5.281,
    defaultLaps: 58,
    raceDistance: 306.183,
    turns: 16,
    firstGrandPrix: 2009,
    lapRecord: "1:26.103",
    lapRecordHolder: "Max Verstappen",
    lapRecordYear: 2021,
    timezone: "Asia/Dubai",
    imageUrl: `${F1_MEDIA_CDN}/f_auto/q_auto/v1677245035/content/dam/fom-website/2018-redesign-assets/Racehub%20header%20images%2016x9/Abu_Dhabi.jpg`,
    miniImageUrl: getCircuitImageUrl("Abu_Dhabi"),
    layoutImageUrl: getCircuitImageUrl("Abu_Dhabi"),
  },
];

async function main() {
  console.log("🏎️  Seeding F1 Tracks...\n");

  for (const track of F1_TRACKS) {
    const existing = await prisma.track.findUnique({
      where: { name: track.name },
    });

    if (existing) {
      // Update existing track with new data
      await prisma.track.update({
        where: { name: track.name },
        data: {
          ...track,
          isActive: true,
        },
      });
      console.log(`  ✅ Updated: ${track.name} (${track.countryCode})`);
    } else {
      // Create new track
      await prisma.track.create({
        data: {
          ...track,
          isActive: true,
        },
      });
      console.log(`  ➕ Created: ${track.name} (${track.countryCode})`);
    }
  }

  console.log(`\n🏁 Seeded ${F1_TRACKS.length} F1 tracks!`);
  
  // Show summary
  const tracks = await prisma.track.findMany({
    where: { isActive: true },
    orderBy: { country: "asc" },
  });
  
  console.log("\n📋 Track Summary:");
  console.log("═".repeat(60));
  tracks.forEach((t) => {
    const flag = countryFlags[t.countryCode || ""] || "🏁";
    console.log(`  ${flag} ${t.shortName?.padEnd(4)} | ${t.name}`);
  });
}

main()
  .catch((e) => {
    console.error("Error seeding tracks:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
