-- Remove CHECK Constraints on Status Fields
-- This script removes the restrictive CHECK constraints from status columns
-- while preserving the column structure (NVARCHAR(50))
-- 
-- Database: TestEngineering
-- Created: September 30, 2025

USE TestEngineering;
GO

PRINT 'Starting removal of CHECK constraints on status fields...';

-- =============================================
-- STEP 0: First, let's see what constraints exist
-- =============================================

PRINT 'Current CHECK constraints on status fields:';

SELECT 
    OBJECT_SCHEMA_NAME(cc.parent_object_id) AS TABLE_SCHEMA,
    OBJECT_NAME(cc.parent_object_id) AS TABLE_NAME,
    c.name AS COLUMN_NAME,
    cc.name AS CONSTRAINT_NAME,
    cc.definition AS CHECK_DEFINITION
FROM sys.check_constraints cc
INNER JOIN sys.columns c ON cc.parent_object_id = c.object_id 
    AND cc.parent_column_id = c.column_id
WHERE (
    (OBJECT_NAME(cc.parent_object_id) = 'Asset_Inventory' AND c.name = 'CurrentStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'ATE_Inventory' AND c.name = 'ATEStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'Fixture_Inventory' AND c.name = 'CurrentStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'Harness_Inventory' AND c.name = 'CurrentStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'Computer_Inventory' AND c.name = 'CurrentStatus')
)
AND OBJECT_SCHEMA_NAME(cc.parent_object_id) = 'dbo';

-- =============================================
-- STEP 1: Find and remove CHECK constraints
-- =============================================

-- First, let's identify the constraint names using the correct system views
-- The constraint names are auto-generated by SQL Server, so we need to find them dynamically

DECLARE @sql NVARCHAR(MAX) = '';

-- Find CHECK constraints using sys.check_constraints and sys.columns
-- This approach uses the correct system catalog views
SELECT @sql = @sql + 'ALTER TABLE [' + OBJECT_SCHEMA_NAME(cc.parent_object_id) + '].[' + OBJECT_NAME(cc.parent_object_id) + '] DROP CONSTRAINT [' + cc.name + '];' + CHAR(13) + CHAR(10)
FROM sys.check_constraints cc
INNER JOIN sys.columns c ON cc.parent_object_id = c.object_id 
    AND cc.parent_column_id = c.column_id
INNER JOIN sys.tables t ON cc.parent_object_id = t.object_id
WHERE (
    (OBJECT_NAME(cc.parent_object_id) = 'Asset_Inventory' AND c.name = 'CurrentStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'ATE_Inventory' AND c.name = 'ATEStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'Fixture_Inventory' AND c.name = 'CurrentStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'Harness_Inventory' AND c.name = 'CurrentStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'Computer_Inventory' AND c.name = 'CurrentStatus')
)
AND OBJECT_SCHEMA_NAME(cc.parent_object_id) = 'dbo';

-- Execute the dynamic SQL to drop constraints
IF LEN(@sql) > 0
BEGIN
    PRINT 'Executing constraint removal commands:';
    PRINT @sql;
    EXEC sp_executesql @sql;
    PRINT 'CHECK constraints removed successfully.';
END
ELSE
BEGIN
    PRINT 'No CHECK constraints found on status columns.';
END

-- =============================================
-- STEP 2: Verify constraint removal
-- =============================================

PRINT 'Verifying constraint removal...';

-- Check for any remaining CHECK constraints on status columns using correct system views
SELECT 
    OBJECT_SCHEMA_NAME(cc.parent_object_id) AS TABLE_SCHEMA,
    OBJECT_NAME(cc.parent_object_id) AS TABLE_NAME,
    c.name AS COLUMN_NAME,
    cc.name AS CONSTRAINT_NAME,
    cc.definition AS CHECK_CLAUSE
FROM sys.check_constraints cc
INNER JOIN sys.columns c ON cc.parent_object_id = c.object_id 
    AND cc.parent_column_id = c.column_id
INNER JOIN sys.tables t ON cc.parent_object_id = t.object_id
WHERE (
    (OBJECT_NAME(cc.parent_object_id) = 'Asset_Inventory' AND c.name = 'CurrentStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'ATE_Inventory' AND c.name = 'ATEStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'Fixture_Inventory' AND c.name = 'CurrentStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'Harness_Inventory' AND c.name = 'CurrentStatus') OR
    (OBJECT_NAME(cc.parent_object_id) = 'Computer_Inventory' AND c.name = 'CurrentStatus')
)
AND OBJECT_SCHEMA_NAME(cc.parent_object_id) = 'dbo';

-- =============================================
-- STEP 3: Verify column structures remain intact
-- =============================================

PRINT 'Verifying column structures are preserved...';

-- Use INFORMATION_SCHEMA.COLUMNS which is correct for column information
SELECT 
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE,
    COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
  AND (
    (TABLE_NAME = 'Asset_Inventory' AND COLUMN_NAME = 'CurrentStatus') OR
    (TABLE_NAME = 'ATE_Inventory' AND COLUMN_NAME = 'ATEStatus') OR
    (TABLE_NAME = 'Fixture_Inventory' AND COLUMN_NAME = 'CurrentStatus') OR
    (TABLE_NAME = 'Harness_Inventory' AND COLUMN_NAME = 'CurrentStatus') OR
    (TABLE_NAME = 'Computer_Inventory' AND COLUMN_NAME = 'CurrentStatus')
  )
ORDER BY TABLE_NAME, COLUMN_NAME;

PRINT 'Status field CHECK constraint removal completed successfully!';
PRINT 'All status columns remain as NVARCHAR(50) but can now accept any values.';

GO